### ISSUE TITLE
oXygen 20.1: XSpec transformation scenario fails

### ISSUE THREAD

**Issue by tofi86** [xspec/oXygen-XML-editor-xspec-support#30]
In oXygen 20.1 the built in transformation scenario for XSpec fails with a message mentioning the XSpec plugin directory.

<details>
 <summary>ERROR</summary>

```
Executing:
"c:\program files\oxygen xml editor 20\jre/bin/java" -Dfile.encoding=UTF-8 -Xmx256m -classpath "C:\Program Files\Oxygen XML Editor 20\tools\ant/lib/ant-launcher.jar" "-Dant.home=C:\Program Files\Oxygen XML Editor 20\tools\ant" org.apache.tools.ant.launch.Launcher -lib "C:\Program Files\Oxygen XML Editor 20\classes" -lib "C:\Program Files\Oxygen XML Editor 20\lib\oxygen.jar" -lib "C:\Program Files\Oxygen XML Editor 20\lib\oxygenAuthor.jar" -lib "C:\Program Files\Oxygen XML Editor 20\lib\oxygenDeveloper.jar" -lib "C:\Program Files\Oxygen XML Editor 20\lib\oxygenEclipse.jar" -lib "C:\Program Files\Oxygen XML Editor 20\lib\oxygenAuthorEclipse.jar" -lib "C:\Program Files\Oxygen XML Editor 20\lib\oxygenDeveloperEclipse.jar" -lib "C:\Program Files\Oxygen XML Editor 20\lib\xml-apis.jar" -lib "C:\Program Files\Oxygen XML Editor 20\lib\resolver.jar" -lib "C:\Program Files\Oxygen XML Editor 20\lib\saxon9ee.jar" -lib "C:\Program Files\Oxygen XML Editor 20\lib\log4j.jar" -lib "C:\Program Files\Oxygen XML Editor 20\lib\xercesImpl.jar" -lib "C:\Program Files\Oxygen XML Editor 20\lib\guava-23.0.jar" -f "build.xml" "-Dcatalog=C:\Users\pagina\parsx3\oxygen-framework\oxygen\xpr-projektdateien\pagina\pc/catalog.xml" "-Dclean.output.dir=false" "-Dtest.type=t" "-Dxspec.fail=false" "-Dxspec.project.dir=C:/Users/pagina/AppData/Roaming/com.oxygenxml/extensions/v20.1/frameworks/https___raw.githubusercontent.com_xspec_oXygen_XML_editor_xspec_support_master_build_update_site.xml/xspec.support-1.0.0/" "-Dxspec.result.html=C:\Users\pagina\GitHub\xspec-test\test/docbook-to-html-result.html" "-Dxspec.xml=C:\Users\pagina\GitHub\xspec-test\test\docbook-to-html.xspec" "-Dwebhelp.trial.license=no"

Buildfile: C:\Users\pagina\AppData\Roaming\com.oxygenxml\extensions\v20.1\frameworks\https___raw.githubusercontent.com_xspec_oXygen_XML_editor_xspec_support_master_build_update_site.xml\xspec.support-1.0.0\build.xml

locateSchematron:

getSchematronPhase:

compileSchematron:

xspec:
     [echo] Creating Test Stylesheet...
     [xslt] Processing C:\Users\pagina\GitHub\xspec-test\test\docbook-to-html.xspec to C:\Users\pagina\GitHub\xspec-test\test\xspec\docbook-to-html.xsl
     [xslt] Loading stylesheet C:\Users\pagina\AppData\Roaming\com.oxygenxml\extensions\v20.1\frameworks\https___raw.githubusercontent.com_xspec_oXygen_XML_editor_xspec_support_master_build_update_site.xml\xspec.support-1.0.0\src\compiler\generate-xspec-tests.xsl

BUILD FAILED
C:\Users\pagina\AppData\Roaming\com.oxygenxml\extensions\v20.1\frameworks\https___raw.githubusercontent.com_xspec_oXygen_XML_editor_xspec_support_master_build_update_site.xml\xspec.support-1.0.0\build.xml:257: java.lang.NoClassDefFoundError: ro/sync/basic/util/Crypto
	at ro.sync.xml.transformer.n.f(Unknown Source)
	at ro.sync.xml.transformer.saxonee.SaxonEEUtilImpl.supplySaxonLicenseAndSchemaResolver(Unknown Source)
	at net.sf.saxon.Configuration.newConfiguration(Unknown Source)
	at net.sf.saxon.s9api.Processor.<init>(Processor.java:66)
	at net.sf.saxon.jaxp.SaxonTransformerFactory.<init>(Unknown Source)
	at net.sf.saxon.TransformerFactoryImpl.<init>(TransformerFactoryImpl.java:46)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at org.apache.tools.ant.taskdefs.optional.TraXLiaison.getFactory(TraXLiaison.java:427)
	at org.apache.tools.ant.taskdefs.optional.TraXLiaison.getSource(TraXLiaison.java:257)
	at org.apache.tools.ant.taskdefs.optional.TraXLiaison.readTemplates(TraXLiaison.java:309)
	at org.apache.tools.ant.taskdefs.optional.TraXLiaison.createTransformer(TraXLiaison.java:328)
	at org.apache.tools.ant.taskdefs.optional.TraXLiaison.transform(TraXLiaison.java:188)
	at org.apache.tools.ant.taskdefs.XSLTProcess.process(XSLTProcess.java:881)
	at org.apache.tools.ant.taskdefs.XSLTProcess.execute(XSLTProcess.java:419)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:857)
	at org.apache.tools.ant.Main.startAnt(Main.java:236)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
Caused by: java.lang.ClassNotFoundException: ro.sync.basic.util.Crypto
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 34 more

Total time: 0 seconds

The process finished with exit code: 1

```
</details>

----

/cc @hschmull @duenckel

**Comment by AlexJitianu** [comment]
The plugin comes with it's own XSpec framework that has it's own set of scenarios (perhaps it would have been better to extend the built-in framework). There was a library missing from the scenario configuration. I fixed the issue and created a new add-on version, 1.0.1.
